pipeline {
    agent {
        node {
            label 'docker-agent-python'
        }
    }
    triggers {
        pollSCM '*/5 * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                cd mypythonapp1
                pip install -r requirements.txt
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                cd mypythonapp1
                python3 hello.py
                python3 hello.py --name=david
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}
