apiVersion: v1
data:
  configMap.txt: "# This is a sample config file that I might use to configure an application\r\nparameter1 = value1\r\nparameter2 = value2"
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-30T10:06:16Z"
  name: my-configmap
  namespace: default
  resourceVersion: "5068967"
  uid: 8caeed50-517c-4caf-b850-36f48a08a55d
